import 'package:flutter/material.dart';
Color gren=Color(0xFF80E2D2);
Color backgroundgren=Color(0xff80E1D1);
Color white=Colors.white;
Color bcolor=Color(0xFF80E1D1);
Color btcolor=Colors.white;
Color tBorder1=Colors.white;
Color tBorder2=Color(0xFF80E1D1);
Color tHint1=Colors.white;
Color tHint2=Color(0xFF80E1D1);
Color circlecolor=Color(0xFF80E1D1);
Color ctn_color=Color(0xff64ACE4);
Color txt_color=Color(0xff2B4D66);
Color circ_color=Color(0xff4a80aa);
Color back_color=Color(0xff4A80AA);
Color backcolor=Color(0xff96B4CB);

///////////////////////////////////
String str_login="Login";
String str_register="Register";
String str_name="Name";
String str_email="Email";
String str_password='Password';
String str_passwordconfirm='Confirm password';
String str_companyname='Companys name';
String str_forgetpassword='Forget your password ?';
String str_code='code';
String str_send='Send';
String str_forogtparagraph1="Enter your registred email bellow ";
String str_forogtparagraph2="to recieve the password code ";
String str_resetpassword='Reset Password';
String str_productid   ='Id';
String str_productname ='Product';
String str_reference   = 'Reference';
String str_length = 'Length';
String str_width  = 'Width';
String str_height = 'Height';
String str_content = 'Quantity';
String str_price   = 'Price';
String str_add  = 'Add';
String str_scan = 'Scan';
String Str_Setting='Setting';
//////////////////////////////////////
String url_image_profile="assets/images/profile.png";
String url_image_logo='assets/images/logo1.png';
String url_image_mail="assets/images/mail.png";
String url_image_lock="assets/images/003-padlock.png";